---
title: Blog Post 3
author: Jordan Ahn, Eui Hyun Kim, Shawn Xu, Wenyan Zhang
date: '2022-10-27'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-20T18:30:49-04:00'
featuredVideo: ~
featuredImage: ~
---

Discuss how the principles for advancing equitable data practice are relevant to your data. I realize that many of the principles require interaction with communities but think about how the principles could be applied if possible.

-Beneficence, respect for persons, and justice. 
-The principles of respect for persons, beneficence, and justice are essential factors to consider when working with the NHANES dataset. The purpose of this dataset is to create a snapshot of the general health of adults and children in the United States through a nationally representative sample. As such, we must ensure that our analyses and conclusions work toward the advancement of public health for the benefit of the national population. Since this data is meant to represent the general populace, it is crucial to keep these principles in mind to uphold the popular interests of the people and to avoid causing harm by analyzing the data through the lens of bias and vested interest. We must keep in mind that faulty conclusions can disproportionately impact marginalized groups, thus necessitating a critical need to practice impartiality in our analysis. Given the subject matter of our analysis question, it is essential that we share any and all results acquired throughout the course of this project. The maintenance and advancement of public health is a massive undertaking relevant to all of us; any and all insights gleaned from analyzing such data can assist in furthering this goal.


For two or three of principles, talk about how they are relevant and what adhering to the practice would entail for your data.

-TALKED ABOUT IN THE PREVIOUS PROMPT


A particularly important principle is transparency. Talk about what might be some limitations of your analysis.

-The goal of our data analysis is to identify health trends and potential problems. Some limitations of our analysis might be biases in variable selection. Since the NHANES dataset has many sub-datasets of different aspects of health, we will be selecting variables that we think are useful for our analysis, which could introduce selection bias to our analysis. Additionally, our variable selection process could also introduce confounding variables, which would weaken our conclusion. 



Discuss the potential for abuse or misuse of the data.

-Information related to demographic information is available for each individual in the NHANES dataset. This demographic dataset includes information related to race, ethnicity, and education status. Given the nature of the available data, it is essential that we practice socially equitable practices in our analyses. Factors such as institutionalized racism and the bias of the data collectors themselves may introduce confounding variables that are effectively impossible to control for, so our analytical methods must account for these limitations. 
