---
title: Blog Post 2
author: Jordan Ahn, Eui Hyun Kim, Shawn Xu, Wenyan Zhang
date: '2022-10-20'
slug: []
categories: []
tags: []
description: ~
toc: yes
authors: []
series: []
lastmod: '2022-10-20T18:30:49-04:00'
featuredVideo: ~
featuredImage: ~
---
```{r}
suppressPackageStartupMessages(library(tidyverse))
```

```{r}
bpdata <- read_csv(here::here("dataset/bpdata.csv"))
#we're gonna be plotting a histogram of blood pressure measurements as well as reporting some descriptive stats for BP
#taking average across the three columns for each type of blood pressure measurement
bpMean <- bpdata %>% mutate(MeanDia = rowMeans(select(.,BPXODI1,BPXODI2,BPXODI3), na.rm = TRUE)) %>% mutate(MeanSys = rowMeans(select(.,BPXOSY1,BPXOSY2,BPXOSY3), na.rm = TRUE))

#making a table of descriptive stats
bpMean %>% select(MeanDia, MeanSys) %>% pivot_longer(everything()) %>% mutate(Blood_Pressure_Type = str_replace(name,"MeanSys","Systolic"), name = str_replace(name,"MeanDia","Diastolic")) %>% group_by(Blood_Pressure_Type) %>% summarise(Mean = mean(value, na.rm = TRUE), Median = median(value, na.rm = TRUE), IQR = IQR(value, na.rm = TRUE)) %>% knitr::kable()
```

```{r}
#making histograms of systolic and diastolic
bpMean %>% ggplot(aes(x = MeanSys, y = ..density..)) +
  geom_histogram(binwidth = 2, colour= "black", fill= "lightblue") +
  geom_vline(aes(xintercept = mean(MeanSys, na.rm = TRUE)),color="black", linetype="dashed", size=1) +
  geom_density(color = "red") +
  labs(title = "Histogram of Systolic Blood Pressure", x = "Systolic Blood Pressure (mmHg)", y = "Density") 

bpMean %>% ggplot(aes(x = MeanDia, y = ..density..)) +
  geom_histogram(binwidth = 2, colour= "black", fill= "lightblue") +
  geom_vline(aes(xintercept = mean(MeanDia, na.rm = TRUE)),color="black", linetype="dashed", size=1) +
  geom_density(color = "red") +
  labs(title = "Histogram of Diastolic Blood Pressure", x = "Diastolic Blood Pressure (mmHg)", y = "Density") 
```