---
title: Three Potential Datasets
author: Jordan Ahn, Eui Hyun Kim, Shawn Xu, Wenyan Zhang
date: '2022-10-12'
slug: []
categories: []
tags: []
description: "In this blog post, we provided three datasets that we will potentially work with. We will describe what each dataset consists of, how the dataset was collected, how large the dataset is, how loadable/clean the dataset is, what direction we could take with each dataset, and what challenges each dataset might have."
toc: yes
authors: []
series: []
lastmod: '2022-10-11T16:41:03-04:00'
featuredVideo: ~
featuredImage: ~
---

\*\*All the Links will be added at the end of the paragraph

The first dataset we propose for use in the final project is the National Health and Nutrition Examination Survey (NHANES). This data is collected on a yearly basis by the Center for Disease Control and Prevention (CDC) for the purpose of assessing the overall health of adults and children in the US. Additionally, the data set is used to track the prevalence of disease and disease risk factors. Individual data points come from a series of interviews and physical examinations in a sample of about 5,000 people that is representative of the entire nation. Interview questions seek to gather information related to demographic, socioeconomic, dietary, and health-related information. The examination component consists of medical, dental, and physiological measurements, as well as laboratory tests administered by medical personnel. The CDC standardized the yearly NHANES data collection process in the 1999-2000 cycle, thus providing about 12 data sets. As mentioned above, there are 5,000 individuals interviewed and examined who make up each row. The data is categorized by 5 different sections: demographics, diet, examination, laboratory, and questionnaire data. Within each of these categories is roughly 10-30 different datasets each with 10 or more variables, bringing the number of total columns accessible to be more than 1,000 different variables. With these extensive, detailed categories, our team is able to ask various questions about health. Our team seeks to analyze health trends over the past 10 years. Additionally, we would like to analyze if there was a significant change in health trends from the pre-pandemic vs. post pandemic time periods. One challenge our team may face is difficulty in joining secondary data. The rows of the NHANES dataset consist of individuals; furthermore, personal information like where the individual is from are not included for privacy reasons. Thus, finding a primary variable could be difficult depending on the nature of the secondary data set. This can be possibly resolved through discovering some kind of joining protocol from the literature or implementing a secondary dataset related to demographic or health information provided by NHANES.

Link: <https://wwwn.cdc.gov/nchs/nhanes/Default.aspx>

------------------------------------------------------------------------

The Substance Abuse & Mental Health Data Archive (SAMHSA) provides mental health client-level data to the public, offered by the U.S. Department of Health and Human Services (HHS). This archive provides a large variety of different mental health-related data sets such as substance abuse/mood disorder prevalence and access to healthcare for mental health issues. A single data set has an average of 6 million rows (each associated with an individual) with 39 columns, and SAMHSA has data archives from 2013 to 2019. Questions answered using this data set would be similar to NHANES, but with a more specific focus on mental health status rather than general health. The included datasets vary. For example, the National Survey on Drug Use and Health (NSDUH) was collected from self-reports so it is entirely dependent on the respondents and their input. This can be a problem because the dataset relies on the honesty of the respondents and their memory. Other datasets are collected from facilities. The goal of retrieving data on substance use and mental health is to track trends of their usage for different mental illnesses and measure/assess these factors in diagnosing/treating patients. The data provided can be downloaded for R and can be easily accessed without additional fees. The main question we wanted to address is to see the trends in drug use and mental health within a time frame. Thus, it is important to include secondary datasets to see how these trends correlate to social factors like the COVID-19 pandemic or during economic fluctuations. In summary, we are trying to profile substance abuse and mental health with factors that affect our school, work, or recreational lives. A challenge that we might face is the aforementioned inconsistencies in self-reported data and the lack of secondary data that is specific enough and fits into our time range. Also, the confidentiality of these datasets could stray us away from the real causes of substance abuse or changes in mental health.

Link: <https://www.datafiles.samhsa.gov/data-sources> Link (2019 Data): <https://www.datafiles.samhsa.gov/dataset/mental-health-client-level-data-2019-mh-Cld-2019-> ds0001

------------------------------------------------------------------------

The Forest Service Research Data (from Kaggle) reports the frequency of wildfires over the course of several years. Shown in the title of the dataset, it has about 1.88 million wildfire cases in the US along with the location of occurrence. Each row is a case, and the data set contains 40 columns. Unfortunately, most columns are character values or subordinate district section names, so it may be challenging to implement this information. The data starts from the year 1992 and is compiled from US federal, state, and local reporting systems. Since the data is organized by region, the risk of forest fire in each region in addition to seasonal timing and fire intensity could be calculated. At this moment, we have not been able to convert the data into a usable form in R. Our team would like to explore the correlation between the prevalence of wildfires and global climate change using this data set. Completing this task would require us to find a secondary data set related to climate change trends in the US. Additionally, we hope to develop an algorithm to predict future wildfires occurring in the US. Finding additional information that is not already provided might prove to be difficult given how specific the data is for location/region (i.e. finding temperature/humidity data for a specific region for the time range for this dataset might not be available). In conclusion, a general summary with this dataset is possible but it might take away the predicting power that we hoped to achieve.

Link: <https://www.kaggle.com/datasets/rtatman/188-million-us-wildfires?resource=download>

